local function MakeModule(HTTPLINK,Name,Parent)
		local module = Instance.new("ModuleScript",Parent)
		module.Name=Name
		module.Source=tostring(game:HttpGet(HTTPLINK))
		warn(module:GetFullName())
		--warn("ModuleSource",module.Source)
	end
	warn("Loading MAIN Module IRIS")
	local IRIS_MAIN_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Main.lua","Iris_SPECIAL_LOAD",game.Players)
	warn("Loading API Module IRIS")
	local API_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/API.lua","API",game.Players.Iris_SPECIAL_LOAD)
	warn("Loading Internal Module IRIS")
	local Internal_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Internal.lua","Internal",game.Players.Iris_SPECIAL_LOAD)
	warn("Loading Types Module IRIS")
	local Types_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Types.lua","Types",game.Players.Iris_SPECIAL_LOAD)
	warn("Loading config Module IRIS")
	local config_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/config.lua","config",game.Players.Iris_SPECIAL_LOAD)
	warn("Loading demoWindow Module IRIS")
	local demoWindow_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/demoWindow.lua","demoWindow",game.Players.Iris_SPECIAL_LOAD)
	warn("Loading Widgets Module IRIS")
	local widgets_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/widgetsmain.lua","widgets",game.Players.Iris_SPECIAL_LOAD)
	warn("Loading Button Module IRIS, Widgets")
	local Button_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Button.lua","Button",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading CheckBox Module IRIS, Widgets")
	local Checkbox_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Checkbox.lua","Checkbox",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Combo Module IRIS, Widgets")
	local Combo_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Combo.lua","Combo",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Format Module IRIS, Widgets")
	local Format_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Format.lua","Format",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Image Module IRIS, Widgets")
	local Image_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Image.lua","Image",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Input Module IRIS, Widgets")
	local Input_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Input.lua","Input",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Menu Module IRIS, Widgets")
	local Menu_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Menu.lua","Menu",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Plot Module IRIS, Widgets")
	local Plot_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Plot.lua","Plot",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading RadioButton Module IRIS, Widgets")
	local RadioButton_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/RadioButton.lua","RadioButton",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Root Module IRIS, Widgets")
	local Root_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Root.lua","Root",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Table Module IRIS, Widgets")
	local Table_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Table.lua","Table",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Text Module IRIS, Widgets")
	local Text_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Text.lua","Text",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Tree Module IRIS, Widgets")
	local Tree_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Tree.lua","Tree",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading Window Module IRIS, Widgets")
	local Window_MODULE_INSTANCE = MakeModule("https://raw.githubusercontent.com/t10underscorekol/JustAutoLoads/refs/heads/main/Widgets/Window.lua","Window",game.Players.Iris_SPECIAL_LOAD.widgets)
	warn("Loading complete")
	return IRIS_MAIN_MODULE_INSTANCE
